version: '3'
services:
  app:
    container_name: banco-digital-webserver
    build: docker
    ports:
        - 8080:80
    volumes:
        - ./:/app
  database:
    container_name: banco-digital-database
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "321321"
      MYSQL_DATABASE: "banco_digital"
    volumes:
      - ./docker/database:/var/lib/mysql